stages:
  data_ingestion:
    cmd: python src/Customer_Churn_Prediction/pipeline/Stage_01_Data_ingestion.py
    deps:
      - src/Customer_Churn_Prediction/pipeline/Stage_01_Data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/Customer-Churn-Records.csv

  data_validation:
    cmd: python src/Customer_Churn_Prediction/pipeline/Stage_02_Data_validation.py
    deps:
      - src/Customer_Churn_Prediction/pipeline/Stage_02_Data_validation.py
      - config/config.yaml
      - artifacts/data_ingestion/Customer-Churn-Records.csv
    outs:
      - artifacts/data_validation/status.txt


  data_transformation:
    cmd: python src/Customer_Churn_Prediction/pipeline/Stage_03_Data_transformation.py
    deps:
      - src/Customer_Churn_Prediction/pipeline/Stage_03_Data_transformation.py
      - config/config.yaml
      - artifacts/data_ingestion/Customer-Churn-Records.csv
      - artifacts/data_validation/status.txt
    outs:
      - artifacts/data_transformation/train.csv
      - artifacts/data_transformation/test.csv


  model_training:
    cmd: python src/Customer_Churn_Prediction/pipeline/Stage_04_Model_training.py
    deps:
      - src/Customer_Churn_Prediction/pipeline/Stage_04_Model_training.py
      - config/config.yaml
      - artifacts/data_transformation/train.csv
    params:
      - DecisionTreeClassifier.criterion
      - DecisionTreeClassifier.max_depth
    outs:
      - model/DecisionTreeClassifier.joblib

  model_evaluation:
    cmd: python src/Customer_Churn_Prediction/pipeline/Stage_05_Model_evaluation.py
    deps:
      - src/Customer_Churn_Prediction/pipeline/Stage_05_Model_evaluation.py
      - config/config.yaml
      - artifacts/data_transformation/test.csv
      - model/DecisionTreeClassifier.joblib
    
    metrics:
    - artifacts/model_evaluation/metrics.json:
        cache: false